pipeline:
  build:
    image: bjodah/bjodahimg20dev:v1.2.0
    environment:
      - CPLUS_INCLUDE_PATH=/opt/boost_1_73_p/include
      - PYCOMPILATION_TESTING_SUNDIALS_CFLAGS="-isystem /opt/sundials-5.3.0-klu-lapack/include"
      - PYCOMPILATION_TESTING_SUNDIALS_LDFLAGS="-Wl,--disable-new-dtags -Wl,-rpath,/opt/sundials-5.3.0-klu-lapack/lib -L/opt/sundials-5.3.0-klu-lapack/lib"
    commands:
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - ./scripts/ci.sh pycompilation
      - PATH=$HOME/.local/bin:$PATH ./scripts/generate_docs.sh
      - ./scripts/prepare_deploy.sh

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]  # 127.0.0.1  192.168.1.99 davycrockett.mooo.com
    port: 22
    user: pycompilation
    secrets: [ rsync_key ]  # secret only set fro event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
