language: python
python:
  - "2.7"
  - "3.4"
#later: - "3.3"
# command to install dependencies
before_install:
  - "sudo apt-get install -qq python-numpy gcc gfortran g++ python-dev python3-dev"
install:
  - "pip install -r requirements.txt"
  - "python -c 'import pycompilation; print(pycompilation.__version__)'"
# command to run tests
script: "PYTHONPATH=`pwd` py.test --pep8 --doctest-modules --ignore setup.py --ignore doc/conf.py --ignore build/"
notifications:
  email: false
