language: python
python:
  - "2.7"
#later: - "3.3"
# command to install dependencies
before_install:
  - "sudo apt-get install -qq python-numpy gcc gfortran g++"
  - "pip install -r requirements.txt"
install:
  - "python setup.py install --user"
# command to run tests
script: py.test
notifications:
  email: false
