package:
  name: pycompilation
  version: "0.4.3.git"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/bjodah/pycompilation
  license:  BSD License
  summary: 'Package for compilation (meta programming).'
