{% set name = "pycompilation" %}
{% set version = "0.5.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  summary: 'Package for compilation (meta programming).'
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
