package:
  name: pycompilation
  version: "0.3.6"

source:
  fn: pycompilation-0.3.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pycompilation/pycompilation-0.3.5.tar.gz
  md5: ca625c8d6e9061a71ff8ddc8c155ed25
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycompilation = pycompilation:main
    #
    # Would create an entry point called pycompilation that calls pycompilation.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pycompilation

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bjodah/pycompilation
  license:  BSD License
  summary: 'Package for compilation (meta programming).'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
