{% set name = "pycompilation" %}
{% set version = GIT_DESCRIBE_TAG | replace("v", "") %}
{% set number = GIT_DESCRIBE_NUMBER | int %}
{% if number > 0 %}
   {% set version = version + ".post" + GIT_DESCRIBE_NUMBER %}
{% endif %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - {{ name }}

about:
  summary: 'Package for compilation (meta programming).'
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
